#
# Spring Properties
#
spring:
    #
    # Application Properties
    #
    application:
        name: nci-evs-api
        
    
    
    
          
    #
    # JSON Formatting Properties
    #
    jackson:
        serialization:
            INDENT_OUTPUT: true
              
   


#
# Management Properties
#
management:
    contextPath: /admin
    

info:
    app:
        name: NCI EVS API
        version: 1.0.0-SNAPSHOT
         




#
# Endpoint Properties
#
endpoints:
    mappings:
        enabled: true

#
# Logging Properties
#
logging:
    level:
        org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:WARN}       
        gov.nih.nci.evs.api: ${LOGGING_LEVEL_GOV_NIH_NCI_EVS_API:DEBUG}
        
  

#
# Server Properties
#
server:  
    port: ${EVS_SERVER_PORT:8080} 
    contextPath: /            
    session:
        persistent: false    

        
nci:
  evs:
    application:
      contextPath: ${NCI_EVS_API_PATH:/api/v1/ctrp}
    stardog:
      url: ${STARDOG_URL:REPLACE_WITH_URL}
      queryUrl: ${STARDOG_QUERY_URL:REPLACE_WITH_QUERY_URL}
      username: ${STARDOG_USERNAME:REPLACE_WITH_USERNAME}
      password: ${STARDOG_PASSWORD:REPLACE_WITH_PASSWORD}     
      readTimeout: ${STARDOG_READ_TIMEOUT:10000}
      connectTimeout: ${STARDOG_CONNECT_TIMEOUT:10000}
      graphName: ${STARDOG_GRAPH_NAME:REPLACE_WITH_GRAPH_NAME} 
      owlfileName: ${STARDOG_OWL_FILENAME:REPLACE_WITH_OWL_FILENAME}
      populateCacheCron: ${POPULATE_CACHE_CRON:0 0 1 * * *}
      forcePopulateCache: ${FORCE_POPULATE_CACHE:N}  
    elasticsearch:
      server:
        url: ${EVS_ELASTIC_SEARCH_SERVER_URL:http://localhost:9200/concept_flat_full_nested/concept/_search}
      query: 
        shortsourcefields: |
            [
            "code",
            "label",
            "displayName",
            "preferredName"
            ]    
        defaultsourcefields: |
            "code",
            "label",  
        associationsourcefields: |
            [
             "code",
             "label",
             "${relation}"
            ] 
        definitionsourcefields: |
            [
             "code",
             "label",
             "definitions"
            ]         
        exactstartswithfields: |
            [ 
            "code.exact^100",          
            "label.exact^100",           
            "displayName.exact^100",          
            "preferredName.exact^100",  
            "synonyms_plain.exact^95", 
            "definitions_plain.exact^70", 
            "semanticTypes.exact^65",  
            "additionalProperties.name.exact^50", 
            "additionalProperties.value.exact^50", 
            "superconcepts.label.exact^45", 
            "subconcepts.label.exact^45",
            "conceptStatus^10"  
            ]
        exactstartswithsynonymfields: |
             [
               "synonyms.termName.exact^100"
             ]
        exactstartswithdefinitionfields: |
             [
               "definitions.description.exact^100"
             ]     
        exactstartswithassociationfields: |
             [
               "${relation}.relatedConceptLabel.exact^100"
             ]         
        containsfields: |
             [
              "code^100",
              "label^100",
              "label.exact^100",
              "label.ngram^50",
              "displayName^100",
              "displayName.exact^100",
              "displayName.ngram^50",
              "preferredName^100",
              "preferredName.exact^100",
              "preferredName.ngram^50",
              "definitions_plain^70",
              "definitions_plain.ngram^30",
              "semanticTypes^10",       
              "synonyms_plain^95",
              "synonyms_plain.exact^95",
              "synonyms_plain.ngram^50",
              "additionalProperties.name^20",
              "additionalProperties.name.ngram^10",
              "additionalProperties.value^20",
              "additionalProperties.value.ngram^10",
              "superconcepts.label^20",
              "superconcepts.label.ngram^10",
              "subconcepts.label^20",
              "subconcepts.label.ngram^10",
              "conceptStatus^10"] 
        containssynonymfields: |
               [
                   "synonyms.termName^100",
                   "synonyms.termName.exact^100",
                   "synonyms.termName.ngram^50"
               ]
        containsdefinitionfields: |
               [
                   "definitions.description^100",
                   "definitions.description.exact^100",
                   "definitions.description.ngram^50"
               ]         
        containsassociationfields: |   
               [
                   "${relation}.relatedConceptLabel^100",
                   "${relation}.relatedConceptLabel.exact^100",
                   "${relation}.relatedConceptLabel.ngram^50"
               ]              
        andorfields: |
              [
               "code^100",
               "label^100",
               "label.exact^100",
               "displayName^100",
               "displayName.exact^100",
               "preferredName^100",
               "preferredName.exact^100",
               "synonyms_plain^95",
               "synonyms_plain.exact^95",
               "definitions_plain^30",
               "semanticTypes^30",
               "additionalProperties.name^30",
               "additionalProperties.value^30",
               "superconcepts.label^25",
               "subconcepts.label^25",
               "conceptStatus^10"
              ]  
        andorsynonymfields: |
              [
                 "synonyms.termName^100",
                 "synonyms.termName.exact^100"
              ]
        andordefinitionfields: |
              [
                 "definitions.description^100",
                 "definitions.description.exact^100"
              ]      
        andorassociationfields: |
              [
                 "${relation}.relatedConceptLabel^100",
                 "${relation}.relatedConceptLabel.exact^100"
              ]  
        statusDefault: |
               "conceptStatus^10",
        P108Default: |
              "preferredName^100",
              "preferredName.exact^100",
        P108Exact: |
              "preferredName.exact^100",
        P108Contains: |       
              "preferredName^100",
              "preferredName.exact^100",
              "preferredName.ngram^50",
        P107Default: |
              "displayName^100",
              "displayName.exact^100",
        P107Exact: |
              "displayName.exact^100",
        P107Contains: |
              "displayName^100",
              "displayName.exact^100",
              "displayName.ngram^50",
        P90Default: |
              "synonyms_plain^95",
              "synonyms_plain.exact^95",
        P90Exact: |
              "synonyms_plain.exact^95",
        P90Contains: |
              "synonyms_plain^95",
              "synonyms_plain.exact^95",
              "synonyms_plain.ngram^50",
        NHC0Default: |
              "code^100",
        NHC0Exact: |
              "code.exact^100",
        NHC0Contains: |
              "code^100",
        P97Default: |
              "definitions_plain^70",
        P97Exact: |
              "definitions_plain.exact^70",
        P97Contains: |      
              "definitions_plain^70",
              "definitions_plain.ngram^30",
        highlightexact: |              
              "code.exact": {},
              "label.exact": {},
              "displayName.exact": {},
              "preferredName.exact": {},
              "definitions_plain.exact": {},
              "semanticTypes.exact": {},
              "synonyms_plain.exact": {},
              "additionalProperties.name.exact": {},
              "additionalProperties.value.exact": {},
              "superconcepts.label.exact": {},
              "subconcepts.label.exact": {},
              "conceptStatus": {}
        highlightsynonymexact: |
               "synonyms.termName.exact": {}  
        highlightdefinitionexact: |
               "definitions.description.exact": {}       
        highlightassociationexact: |
               "${relation}.relatedConceptLabel.exact": {}    
        highlightcontains: |
              "code": {},
              "label.ngram": {},
              "displayName.ngram": {},     
              "preferredName.ngram": {},
              "definitions_plain.ngram": {},
              "semanticTypes": {},
              "synonyms_plain.ngram": {},
              "additionalProperties.name.ngram": {},
              "additionalProperties.value.ngram": {},
              "superconcepts.label.ngram": {},
              "subconcepts.label.ngram": {},
              "conceptStatus": {}  
        highlightsynonymcontains: |
               "synonyms.termName.ngram": {} 
        highlightdefinitioncontains: |
               "definitions.description.ngram": {}        
        highlightassociationcontains: |
               "${relation}.relatedConceptLabel.ngram": {}                 
        highlightandor: | 
               "code": {},
               "label": {},
               "displayName": {},
               "preferredName": {},
               "definitions_plain": {},
               "semanticTypes": {},
               "synonyms_plain": {},
               "additionalProperties.name": {},
               "additionalProperties.value": {},
               "superconcepts.label": {},
               "subconcepts.label": {},
               "conceptStatus": {}
        highlightsynonymandor: |
                "synonyms.termName": {}   
        highlightdefinitionandor: |
                "definitions.description": {}           
        highlightassociationandor: |
                "${relation}.relatedConceptLabel": {}                  
        mainQuery: |
              {
                  "_source": ${sourcefields},                  
                  "from": ${fromRecord},
                  "size": ${pageSize},
                  "query": {
                    "bool": {
                      "must": {
                        "query_string": {
                          "query": "${term}",
                          ${operator}
                          "fields": ${fields}
                        }
                      }
                      ${filter}
                    }
                  },
                  "highlight": {
                    ${highlightTags}
                    "fields": {
                      ${highlightFields}         
                    }
                  },
                  "aggs": {
                    "isDisease": {
                      "terms": {
                        "field": "isDisease"
                      }
                    },
                    "isBiomarker": {
                      "terms": {
                        "field": "isBiomarker"
                      }
                    },
                    "conceptStatus": {
                      "terms": {
                        "field": "conceptStatus"
                      }
                    }
                  }
                } 
        mainNestedQuery: |
                {
                  "_source": ${sourcefields},                  
                  "from": ${fromRecord},
                  "size": ${pageSize},
                  "query": {
                     "nested": {
                        "path": "${nestedPath}",
                           "query": {
                              "bool": {
                                 "must": [
                                    { "multi_match" : {
                                     "query": "${term}",
                                      ${operator}
                                     "fields":     ${fields}
     
                                     }}
                                     ${searchFilter}
                                    ]
                    
                    }
                    }                      
                    }
                  },
                  "highlight": {
                    ${highlightTags}
                    "fields": {
                      ${highlightFields}         
                    }
                  },
                  "aggs": {
                    "isDisease": {
                      "terms": {
                        "field": "isDisease"
                      }
                    },
                    "isBiomarker": {
                      "terms": {
                        "field": "isBiomarker"
                      }
                    },
                    "conceptStatus": {
                      "terms": {
                        "field": "conceptStatus"
                      }
                    }
                  }
                }                        
        mainQueryWithoutHighlights: | 
                {
                  "_source": ${sourcefields},                  
                  "from": ${fromRecord},
                  "size": ${pageSize},
                  "query": {
                    "bool": {
                      "must": {
                        "query_string": {
                          "query": "${term}",
                          ${operator}
                          "fields": ${fields}
                        }
                      }
                      ${filter}
                    }
                  },
                  "aggs": {
                    "isDisease": {
                      "terms": {
                        "field": "isDisease"
                      }
                    },
                    "isBiomarker": {
                      "terms": {
                        "field": "isBiomarker"
                      }
                    },
                    "conceptStatus": {
                      "terms": {
                        "field": "conceptStatus"
                      }
                    }
                  }
                } 
        mainNestedQueryWithoutHighlights: |
                {
                  "_source": ${sourcefields},                  
                  "from": ${fromRecord},
                  "size": ${pageSize},
                  "query": {
                     "nested": {
                        "path": "${nestedPath}",
                           "query": {
                              "bool": {
                                 "must": [
                                    { "multi_match" : {
                                     "query": "${term}",
                                      ${operator}
                                     "fields":     ${fields}
     
                                     }} 
                                     ${searchFilter}
                                    ]
                    
                    }
                    }                      
                    }
                  },
                  "aggs": {
                    "isDisease": {
                      "terms": {
                        "field": "isDisease"
                      }
                    },
                    "isBiomarker": {
                      "terms": {
                        "field": "isBiomarker"
                      }
                    },
                    "conceptStatus": {
                      "terms": {
                        "field": "conceptStatus"
                      }
                    }
                  }
                } 
        highlightTags: |
            "pre_tags": [
                      "<font color='#428bca'><strong>"
                    ],
                    "post_tags": [
                      "</strong></font>"
                    ],      
                    