#
# Spring Properties
#
spring:
  #
  # Application Properties
  #
  application:
    name: nci-evs-api
  #profiles:
  #  include: metadata

  #
  # JSON Formatting Properties
  #
  jackson:
    serialization:
      INDENT_OUTPUT: true

  cache:
    jcache:
      config: classpath:ehcache.xml

  # Term Form Mail Server Properties
  mail:
    host: ${MAIL_HOST:mailfwd.nih.gov}
    port: 25
    username: ${MAIL_USER:REPLACE_WITH_USERNAME}
    password: ${MAIL_PASSWORD:REPLACE_WITH_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_AUTH:true}
          starttls:
            enable: ${MAIL_TLS:true}

management:
  endpoints:
    web:
      exposure:
        include: heapdump,liquibase,loggers,prometheus,threaddump,info,metrics,health

#
# TODO: need to inject this into the application and use in VersionController, currently ignored
#
info:
  app:
    name: NCI EVS API
    version: 1.1.2.RELEASE

#
# Logging Properties
#
logging:
  level:
    org.springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK:WARN}
    gov.nih.nci.evs.api: ${LOGGING_LEVEL_GOV_NIH_NCI_EVS_API:INFO}
    org.springframework.data.elasticsearch.core: ${LOGGING_LEVEL_SPRING_DATA_ES:INFO}
    org.springframework.data.opensearch.core: ${LOGGING_LEVEL_SPRING_DATA_ES:INFO}
    gov.nih.nci.evs.api.configuration.EVSOpenSearchRestTemplate: ${LOGGING_LEVEL_SPRING_DATA_ES:INFO}

#
# Server Properties
#
server:
  port: ${EVS_SERVER_PORT:8080}
  servlet:
    context-path: /
    session:
      persistent: false


#
# Application Properties
#
nci:
  evs:
    application:
      adminKey: ${NCI_EVS_ADMIN_KEY:Default}
      contextPath: ${NCI_EVS_API_PATH:/api/v1}
      metricsEnabled: ${METRICS_ENABLED:false}
      metricsDir: ${METRICS_DIR}
      configBaseUri: ${CONFIG_BASE_URI:https://raw.githubusercontent.com/NCIEVS/evsrestapi-operations/main/config/metadata}
      uiLicense: ${UI_LICENSE:ui-license}
      unitTestData: ${UNIT_TEST_DATA:../data/UnitTestData/}
      childhoodNeoplasmSubsetsXls: ${CHILDHOOD_NEOPLASM_SUBSETS_XLS:Childhood_Neoplasm_Subsets.xls}
      ftpNeoplasmUrl: ${FTP_NEOPLASM_URL:https://evs.nci.nih.gov/ftp1/NCI_Thesaurus/Neoplasm/}
    bulkload:
      conceptsDir: ${NCI_EVS_BULK_LOAD_CONCEPTS_DIR:/tmp/}
      lockFile: ${NCI_EVS_BULK_LOAD_LOCK_FILE_NAME:DownloadSuccessfull.lck}
      downloadBatchSize: ${NCI_EVS_BULK_LOAD_DOWNLOAD_BATCH_SIZE:1000}
      indexBatchSize: ${NCI_EVS_BULK_LOAD_INDEX_BATCH_SIZE:1000}
      graphDbs: CTRP,NCIT2
    graph:
      host: ${GRAPH_DB_HOST:localhost}
      port: ${GRAPH_DB_PORT:3030}
      db: ${GRAPH_DB:NCIT2}
      queryUrl: ${GRAPH_DB_MONTHLY_QUERY_URL:http://${nci.evs.graph.host}:${nci.evs.graph.port}/${nci.evs.graph.db}/query}
      username: ${GRAPH_DB_USERNAME:REPLACE_WITH_USERNAME}
      password: ${GRAPH_DB_PASSWORD:REPLACE_WITH_PASSWORD}
      readTimeout: ${GRAPH_DB_READ_TIMEOUT:60}
      connectTimeout: ${GRAPH_DB_CONNECT_TIMEOUT:60}
    opensearch:
      server:
        host: ${ES_HOST:localhost}
        port: ${ES_PORT:9201}
        scheme: ${ES_SCHEME:http}
      timeout: 240000
    sparql:
      timeoutSeconds: 60

# Springdoc
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha
    doc-expansion: none
    syntaxHighlight:
      activated: false

# Google Recaptcha
google:
  recaptcha:
    site:
      key: ${RECAPTCHA_KEY:REPLACE_WITH_KEY}
    secret:
      key: ${RECAPTCHA_SECRET:REPLACE_WITH_SECRET}
    verify:
      url: https://www.google.com/recaptcha/api/siteverify