name: Trivy Vulnerability Scan

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
      - develop-*
      - master

  workflow_dispatch: # Allows manual runs from the GitHub UI

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Generate dependency lock for scanning
      - name: Generate dependency lock for scanning
        run: ./gradlew dependencies --write-locks

      # Install Trivy
      - name: Install Trivy
        run: |
          TRIVY_LATEST_VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | jq -r .tag_name)
          wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_LATEST_VERSION}/trivy_${TRIVY_LATEST_VERSION#v}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_LATEST_VERSION#v}_Linux-64bit.deb

      # Run Trivy scan
      - name: Run Trivy scan
        id: trivy-scan
        run: trivy fs gradle.lockfile --scanners vuln --severity HIGH,CRITICAL --format json --output trivy_report.json --exit-code 0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db

      # Check and output vulnerabilities
      - name: Check and output vulnerabilities
        id: check-vulnerabilities
        run: |
          vuln_count=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH" or .Severity == "CRITICAL")] | length' trivy_report.json)
          echo "Vulnerability count: $vuln_count"
          if [ "$vuln_count" -gt 0 ]; then
            echo "High or Critical vulnerabilities found!"
            jq -r '.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH" or .Severity == "CRITICAL") | "\(.VulnerabilityID): \(.PkgName) - Severity: \(.Severity) - Installed Version: \(.InstalledVersion) - Fixed Version: \(.FixedVersion)"' trivy_report.json
            exit 1
          else
            echo "No high or critical vulnerabilities found."
          fi

      # Remove generated dependency locks
      - name: Remove generated dependency locks
        if: always()
        run: |
          rm -rf gradle/dependency-locks
          rm -f gradle.lockfile
  image-scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'  # Use Eclipse Temurin distribution for Java

      # Build application image
      - name: Build application image
        run: make docker DOCKER_IMAGE=evsrestapi:ci

      # Install Trivy
      - name: Install Trivy
        run: |
          TRIVY_LATEST_VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | jq -r .tag_name)
          wget https://github.com/aquasecurity/trivy/releases/download/${TRIVY_LATEST_VERSION}/trivy_${TRIVY_LATEST_VERSION#v}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_LATEST_VERSION#v}_Linux-64bit.deb

      # Scan application image
      - name: Scan application image
        id: image-trivy-scan
        run: trivy image evsrestapi:ci --scanners vuln --severity HIGH,CRITICAL --format json --output trivy_image_report.json --exit-code 0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db

      # Check and output image vulnerabilities
      - name: Check and output image vulnerabilities
        id: check-image-vulnerabilities
        run: |
          vuln_count=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH" or .Severity == "CRITICAL")] | length' trivy_image_report.json)
          echo "Image vulnerability count: $vuln_count"
          if [ "$vuln_count" -gt 0 ]; then
            echo "High or Critical image vulnerabilities found!"
            jq -r '.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH" or .Severity == "CRITICAL") | "\(.VulnerabilityID): \(.PkgName) - Severity: \(.Severity) - Installed Version: \(.InstalledVersion) - Fixed Version: \(.FixedVersion)"' trivy_image_report.json
            exit 1
          else
            echo "No high or critical image vulnerabilities found."
          fi
